name: Build and deploy Azure Functions

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'onlinecourse-product-api'
  DOTNET_VERSION: '8.0.x'
  CONFIGURATION: 'Release'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore OnlineCourseFunctions.csproj
      
      - name: Build with metadata generation
        run: |
          dotnet build OnlineCourseFunctions.csproj \
          --configuration ${{ env.CONFIGURATION }} \
          --no-restore \
          /p:GenerateFunctionsMetadata=true
      
      - name: Publish application
        run: |
          dotnet publish OnlineCourseFunctions.csproj \
          --configuration ${{ env.CONFIGURATION }} \
          --output ./published \
          --no-build \
          /p:GenerateFunctionsMetadata=true
      
      - name: Verify deployment package
        run: |
          echo "Checking published files:"
          dir ./published
          echo "Checking for function metadata:"
          find ./published -name "*.json" | grep -i function
      
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./published
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: false  # Disable redundant build
