name: Build and deploy Azure Functions

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'onlinecourse-product-api'
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Find project file
        id: find-project
        run: |
          # Search for .csproj file (case-insensitive)
          PROJECT_PATH=$(find . -iname "*.csproj" -type f -print -quit)
          echo "PROJECT_PATH=${PROJECT_PATH}" >> $GITHUB_OUTPUT
          echo "Found project file at: ${PROJECT_PATH}"
      
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore "${{ steps.find-project.outputs.PROJECT_PATH }}"
      
      - name: Build solution
        run: |
          dotnet build "${{ steps.find-project.outputs.PROJECT_PATH }}" \
          --configuration ${{ env.CONFIGURATION }} \
          --no-restore \
          /p:GenerateFunctionsMetadata=true
      
      - name: Publish application
        run: |
          dotnet publish "${{ steps.find-project.outputs.PROJECT_PATH }}" \
          --configuration ${{ env.CONFIGURATION }} \
          --output ./published \
          --no-build \
          /p:GenerateFunctionsMetadata=true
      
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./published
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
